### ISSUE TITLE
Extract lat, lon from RTree

### ISSUE THREAD

**Issue by IvanaEscobar** [CNES/pangeo-pyinterp#13]
**Is your feature request related to a problem? Please describe.**
When using RTree, we can extract distances and values of nearest neighbors (for example when using the [query method](https://pangeo-pyinterp.readthedocs.io/en/latest/generated/pyinterp.RTree.query.html#pyinterp.RTree.query)). Currently, there is no way to get the (lon, lat) position of the nearest neighbors through the method. 

I am interested in finding the (lon, lat) coordinates of the nearest neighbors using any of the RTree methods.

**Describe the solution you'd like**
Return the position in the query method in addition to the standard output of distance in meters and the value of the different neighbors. 

**Describe alternatives you've considered**
Loop through the data without RTree to calculate the spheroidal distances to the point of interest ($$$), then compare distances with query method results to save (lon, lat) pairs 💀

**Additional context**
There may already be a process for this, but I couldn't find anything in the PyInterp Read the Docs

**Comment by fbriol** [comment]
Thanks for your feedback.

I have completed your request for the next version which should be released soon. The RTree object now has a  `value` method that returns to the k-nearest neighbors, their coordinates and the associated values.

Ref: 72a48f84e50e01214461ec6c894aed24e0c029aa
