### ISSUE TITLE
Python kernel crashes when running "ex_geohash.py" example

### ISSUE THREAD

**Issue by fredpeertje** [CNES/pangeo-pyinterp#15]
**Describe the bug**
Python kernel crashes when running [ex_geohash example.](https://github.com/CNES/pangeo-pyinterp/blob/master/examples/ex_geohash.py). 

```
python(23293,0x1159de600) malloc: *** error for object 0x7ff7b6c160a8: pointer being freed was not allocated
python(23293,0x1159de600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python ex_geohash.py
```

**Pyinterp/Numpy/Python version information**
I run Python 3.10.6 with the following packages
```
  - cartopy==0.21.0
  - contourpy==1.0.5
  - cycler==0.11.0
  - fonttools==4.38.0
  - gdal==3.4.1 and libgdal=3.4.1
  - kiwisolver==1.4.4
  - matplotlib==3.6.1
  - pillow==9.2.0
  - pyproj==3.4.0
  - pyqt5-sip==12.11.0
  - pyshp==2.3.1
  - shapely==1.8.5.post1
  - numpy=1.23.4
  - ipykernel=6.15.2
  - ipython=8.4.0
```

**Additional context**

**Comment by fbriol** [comment]
What platform did you run the code on?

**Comment by fredpeertje** [comment]
> What platform did you run the code on? What version of the library?

MacOS Monterey 12.3.1

**Comment by fbriol** [comment]
I can't reproduce your error or even detect a problem. Are you using an Intel or Apple processor?
