### ISSUE TITLE
Support intel_openmp package

### ISSUE THREAD

**Issue by DManowitz** [CNES/pangeo-pyinterp#16]
**Is your feature request related to a problem? Please describe.**
On conda-forge, this package requires the llvm-openmp package, which conflicts with the intel-openmp package.

**Describe the solution you'd like**
I'd like a version of this package which supports the intel-openmp package, which is required for some packages, such as pytorch.

**Comment by fbriol** [comment]
https://github.com/conda-forge/pyinterp-feedstock/pull/81
