### ISSUE TITLE
Support mkl 2023

### ISSUE THREAD

**Issue by DManowitz** [CNES/pangeo-pyinterp#17]
**Is your feature request related to a problem? Please describe.**
The latest version of pyinterp on conda-forge is limited to mkl <2023.  However, mkl 2023 is now available.

**Describe the solution you'd like**
A package available on conda-forge which supports mkl 2023.

**Comment by fbriol** [comment]
Normally, the new version 2023.2.0 should solve your problem.

**Comment by DManowitz** [comment]
Unfortunately, the package on conda-forge still shows <2023.0a0 as the upper limit for mkl.

**Comment by fbriol** [comment]
I tried to build the package by asking for MKL 2023 as a prerequisite, unfortunately the build failed because mamba could not resolve all the dependencies. We have to wait for the migration of all packages to this new version.

**Comment by fbriol** [comment]
Ignores the previous message. I have corrected the construction recipe. The tests are in progress. Normally by tomorrow we will have the corrected version.

**Comment by DManowitz** [comment]
Thank you!
