### ISSUE TITLE
Wrong kwarg fitting_model value in bicubic function

### ISSUE THREAD

**Issue by marceloandrioni** [CNES/pangeo-pyinterp#19]
**Describe the bug**

Hello, not a big problem, but I noticed that the docstring for the bicubic function shows `bicubic` as the default value for the `fitting_model` parameter ([link](https://github.com/CNES/pangeo-pyinterp/blob/master/src/pyinterp/interpolator/bicubic.py#L54)), while in the function declaration, `c_spline` is the default ([link](https://github.com/CNES/pangeo-pyinterp/blob/master/src/pyinterp/interpolator/bicubic.py#L23)).

I thought of doing a simple PR to fix this, but I am not sure which one is to be used as default.

Thank you.

**Comment by fbriol** [comment]
Thank you for your feedback. I'm willing to let you do a PR by changing the default value to 'bicubic' [here](https://github.com/CNES/pangeo-pyinterp/blob/665652a313dfbec5fb81feb5f9756f1b92ca88d5/src/pyinterp/interpolator/bicubic.py#L23).

Thank you very much for your contribution.
