### ISSUE TITLE
openblas package in conda is wrongly linking to mkl

### ISSUE THREAD

**Issue by espiritocz** [CNES/pangeo-pyinterp#24]
hi,

please fix the conda-forge build:
 pyinterp  2023.2.1  openblas_py38hf1160e9_101

it is actually mkl version of the build.
please provide openblas build package to conda-forge.

thanks

**Comment by fbriol** [comment]
Fixed in the conda-forge build 2023.5.0

**Comment by espiritocz** [comment]
thank you, it works now!
(great job)
