### ISSUE TITLE
Understanding trivariate interpolator

### ISSUE THREAD

**Issue by benstadin** [CNES/pangeo-pyinterp#25]
I‘m looking for something similar to the regular grid interpolator in SciPy [1]. How does the trivariate interpolator compare, algorithmically and from practical application perspective?

[1] https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RegularGridInterpolator.html#scipy.interpolate.RegularGridInterpolator

**Comment by fbriol** [comment]
Hello,

Thanks for reaching out! The key distinction with our interpolation routine compared to the scipy counterpart is its ability to handle geodesic grids. The axes in play are latitudes and longitudes. So, when a grid point lies on both sides of the 0/360 boundary, our interpolation routine gracefully manages this scenario, utilizing grid points on either side of the boundary. In contrast, scipy's interpolation operates in a Cartesian model, lacking the capability to handle such cases effectively, especially when dealing with points on this boundary.

Hope this clarifies the differences for you. Feel free to reach out if you have more questions or need further clarification.

Best regards,
Frederic.
