### ISSUE TITLE
pyinterp.fill error and error in doc

### ISSUE THREAD

**Issue by Marston** [CNES/pangeo-pyinterp#26]
Errors:
```
Exception has occurred: AttributeError
module 'pyinterp' has no attribute 'tests'
  File "/root/lastfocus/goes_abi_geo_read.py", line 19, in <module>
    ds = pyi.tests.load_grid2d()
         ^^^^^^^^^
AttributeError: module 'pyinterp' has no attribute 'tests'
```
**To Reproduce**
Copy code from [Documentation](https://pangeo-pyinterp.readthedocs.io/en/latest/auto_examples/ex_fill_undef.html#sphx-glr-auto-examples-ex-fill-undef-py)
```python

import pyinterp as pyi
import pyinterp.fill as pf

ds = pyinterp.tests.load_grid2d()
grid = pyinterp.backends.xarray.Grid2D(ds.mss)
```

Trying to take a 2D data on a regular grid (regional map) that contains some missing values and I would like to use pyinterp.fill.loess to do it. Not sure how the data shape is suppose to be.

**Comment by fbriol** [comment]
Hi there!

It looks like there might be a small mistake in your code. Instead of:

```python
import pyinterp as pyi
import pyinterp.fill as pf

ds = pyi.tests.load_grid2d()
grid = pyi.backends.xarray.Grid2D(ds.mss)
```

Try the following:

```python
import pyinterp.backends.xarray
import pyinterp.fill
import pyinterp.tests

ds = pyinterp.tests.load_grid2d()
grid = pyinterp.backends.xarray.Grid2D(ds.mss)
```

It seems you were importing pyinterp.tests incorrectly. Give this a shot, and let me know if it resolves the issue. If you encounter any more problems, feel free to ask!
