### ISSUE TITLE
Install CMakeLists.txt not found

### ISSUE THREAD

**Issue by mmann1123** [CNES/pangeo-pyinterp#3]
Im running Ubuntu 18.04. I'm stuck on one error for install and hoping you can point me in the right direction. From the help files I can't seem to find a way to set a path, and/or can't figure our which library needs to be installed to add BLAS.  

python setup.py build --boost-root /usr/lib/x86_64-linux-gnu/ --gsl-root /usr/lib/x86_64-linux-gnu/ --eigen-root /home/mmann1123/anaconda3/envs/geowombat/lib/python3.7/site-packages/scipy/sparse/linalg/eigen --mkl-root /home/mmann1123/anaconda3/envs/geowombat/lib/ 

running build
running build_py
copying src/pyinterp/version.py -> build/lib.linux-x86_64-3.7/pyinterp
running build_ext
cmake /home/mmann1123/Documents/github/pangeo-pyinterp -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mmann1123/Documents/github/pangeo-pyinterp/build/lib.linux-x86_64-3.7/pyinterp -DPYTHON_EXECUTABLE=/home/mmann1123/anaconda3/envs/geowombat/bin/python -DBOOSTROOT=/usr/lib/x86_64-linux-gnu/ -DGSL_ROOT_DIR=/usr/lib/x86_64-linux-gnu/ -DEIGEN3_INCLUDE_DIR=/home/mmann1123/anaconda3/envs/geowombat/lib/python3.7/site-packages/scipy/sparse/linalg/eigen
-- Build type: Release
-- Boost version: 1.65.1
-- A library with BLAS API not found. Please specify library location.
CMake Error at CMakeLists.txt:190 (add_subdirectory):
  The source directory

    /home/mmann1123/Documents/github/pangeo-pyinterp/third_party/googletest

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:200 (add_subdirectory):
  The source directory

    /home/mmann1123/Documents/github/pangeo-pyinterp/third_party/pybind11

  does not contain a CMakeLists.txt file.

CMake Error at src/pyinterp/core/CMakeLists.txt:13 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!
See also "/home/mmann1123/Documents/github/pangeo-pyinterp/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/mmann1123/Documents/github/pangeo-pyinterp/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

**Comment by fbriol** [comment]
You probably forgot to initialize the GIT submodules:
```bash
git submodule update --init
```
