### ISSUE TITLE
ImportError: libomp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NMC-DAVE** [CNES/pangeo-pyinterp#4]
Hi:
   I install pyinterp with "conda install pyinterp -c conda-forge" in ubuntu 19.10 system. When I import the library, I got the following errors:
```
>>> import pyinterp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/pyinterp/__init__.py", line 6, in <module>
    from .axis import TemporalAxis
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/pyinterp/axis.py", line 12, in <module>
    from . import core
ImportError: libomp.so: cannot open shared object file: No such file or directory
```

So how can I solve this problem, thanks very much.

**Comment by fbriol** [comment]
There is a problem of dependency between `conda-forge` and the main channel of `conda`. You can install the package `llvm-openmp`:
```
conda install -c conda-forge llvm-openmp
```
or upgrade all packages in your distribution to conda-forge
```
conda upgrade --all -c conda-forge
```
