### ISSUE TITLE
`No such file or directory` Error on Pip Install

### ISSUE THREAD

**Issue by AyrtonB** [CNES/pangeo-pyinterp#6]
**Describe the bug**
Receiving an error when trying to pip install pyinterp

error: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-0uuc34iv\\pyinterp\\third_party\\unqlite\\unqlite.h'

**To Reproduce**
`pip install pyinterp`

```
**Pyinterp/Numpy/Python version information**

numpy version: 1.19.4
sys version: 3.7.8

**Comment by fbriol** [comment]
The installation with the *pip* command is not supported. This project uses a lot of C++ code which is built using *CMake*. The ``setup.py`` file is used to drive *CMake* to build the library, manage dependencies and install the Python library.

The easiest way is to use ``conda`` to install the library. If you have the Microsoft C++ compiler installed on your computer, you can build the library from the Conda build script located in the ``conda`` directory. This directory is visible only if you made a clone of the repository.

If you have all the prerequisites installed on your computer, you can also launch the construction with the script ``setup.py``.

But if you are not familiar with handling compiled code, the easiest way is to do the installation with Conda.

**Comment by AyrtonB** [comment]
Thank you for the explanation, I'm trying to use it within a GitHub action so the conda install sounds easiest.

Thanks!

**Comment by vedal** [comment]
Sorry for reviving this thread, but I'd like to file a feature request for a pre-built version installable through pypi (with pip).

**Comment by fbriol** [comment]
I modified the installation script to allow building the library without using Conda. For this to work the dependencies must be installed on your system. I tested this modification on my Linux station. Not elsewhere. The sources on [pypi](https://pypi.org/project/pyinterp/) are up to date and in the main branch of the GIT repository.
