### ISSUE TITLE
Support for Apple silicon

### ISSUE THREAD

**Issue by YvZheng** [CNES/pangeo-pyinterp#8]
Hope to support apple m1.

**Comment by fbriol** [comment]
As soon as this platform is available on Azure, likely this summer, we will be able to activate this build. For the moment it is only possible to do a cross-compilation, but not to test the library.

**Comment by jejjohnson** [comment]
Any updates for this?

**Comment by fbriol** [comment]
The construction of the package is under construction on [conda-forge](https://github.com/conda-forge/pyinterp-feedstock). You should probably see the new build within a few hours.

The package is built using cross-compilation tools without running a single test. The only thing I know is that the build has finished successfully.

You can run the library tests, they are embedded in the module. To do this, run the command: ``pytest --pyargs pyinterp``

I close this pull request. Feel free to reopen it or create a new one to report problems.

**Comment by jejjohnson** [comment]
Thank you very much @fbriol , everything works now!
